### ISSUE TITLE
Methods should be chainable

### ISSUE THREAD

**Issue by manthanhd** [manthanhd/talkify#10]
``` javascript
// proposed
new Bot().train(topic, sentence).addSkill(skill).resolve(....)

// current
var bot = new Bot();
bot.train(topic, sentence);
bot.addSkill(skill);
bot.resolve(....);
```

**Comment by codeavenger07** [comment]
Mind if I take a stab at this?

**Comment by jomarquez** [comment]
i'll give it a shot.

**Comment by rafaelklaessen** [comment]
Isn't it just enough to add `return this;` in the function? It will return the original Bot object so that all other methods are still defined.

**Comment by manthanhd** [comment]
@rafaelklaessen you are right. See pull request #17 for updates.

**Comment by manthanhd** [comment]
Closing as @marekhakala's merge request has been merged.
