### ISSUE TITLE
Allow skills to mark response as final to prevent going next

### ISSUE THREAD

**Issue by manthanhd** [manthanhd/talkify#3]
Something like:
```javascript
response.message = new SingleLineMessage('We\'ve mailed the product to you');
response.final();
return next()
```

**Comment by manthanhd** [comment]
I should also be able to mark response as final without providing a message in which case up to previous skill's message is considered.

**Comment by xRahul** [comment]
Hey @manthanhd 

Can you some readme to the project to show general details and setup instructions?

**Comment by manthanhd** [comment]
@xRahul Done. Let me know how you find it. 😃

**Comment by xRahul** [comment]
@manthanhd looks good! I'll check it out
