### ISSUE TITLE
Support for non-English locales

### ISSUE THREAD

**Issue by jay-at-avido** [manthanhd/talkify#35]
Can this tool be used to build conversations in languages other than English?
If so, what could be some possible limitations?

**Comment by newmips** [comment]
Yes. You must simply define skills that match your language.

**Comment by manthanhd** [comment]
Sorry for delayed response. I agree with @newmips to a degree. The answer depends on the classifier that you are using. The built in ones should work regardless of the language however, if you choose something like IBM Watson, it **might** have language specific logic for classification which could prevent it from working with multiple (or different) languages.
